// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinkyShopProject.Business.Context;

#nullable disable

namespace MinkyShopProject.Business.Migrations
{
    [DbContext(typeof(MinkyShopDbContext))]
    partial class MinkyShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinkyShopProject.Business.Entities.BienThe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<float>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 2, 14, 0, 56, 3, 152, DateTimeKind.Local).AddTicks(7021));

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdSanPham");

                    b.ToTable("BienThe", (string)null);
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.BienTheChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<Guid>("IdBienThe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGiaTri")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThuocTinhSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdBienThe");

                    b.HasIndex("IdGiaTri");

                    b.HasIndex("IdThuocTinhSanPham");

                    b.ToTable("BienTheChiTiet", (string)null);
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.GiaTri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<Guid>("IdThuocTinh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdThuocTinh");

                    b.ToTable("GiaTri", (string)null);
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 2, 14, 0, 56, 3, 153, DateTimeKind.Local).AddTicks(1431));

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.ThuocTinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 2, 14, 0, 56, 3, 153, DateTimeKind.Local).AddTicks(2093));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("ThuocTinh", (string)null);
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.ThuocTinhSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThuocTinh")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdThuocTinh");

                    b.ToTable("ThuocTinhSanPham", (string)null);
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.BienThe", b =>
                {
                    b.HasOne("MinkyShopProject.Business.Entities.SanPham", "SanPham")
                        .WithMany("BienThes")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.BienTheChiTiet", b =>
                {
                    b.HasOne("MinkyShopProject.Business.Entities.BienThe", "BienThe")
                        .WithMany("BienTheChiTiets")
                        .HasForeignKey("IdBienThe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShopProject.Business.Entities.GiaTri", "GiaTri")
                        .WithMany("BienTheChiTiets")
                        .HasForeignKey("IdGiaTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShopProject.Business.Entities.ThuocTinhSanPham", "ThuocTinhSanPham")
                        .WithMany("BienTheChiTiets")
                        .HasForeignKey("IdThuocTinhSanPham")
                        .IsRequired();

                    b.Navigation("BienThe");

                    b.Navigation("GiaTri");

                    b.Navigation("ThuocTinhSanPham");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.GiaTri", b =>
                {
                    b.HasOne("MinkyShopProject.Business.Entities.ThuocTinh", "ThuocTinhs")
                        .WithMany("GiaTris")
                        .HasForeignKey("IdThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThuocTinhs");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.ThuocTinhSanPham", b =>
                {
                    b.HasOne("MinkyShopProject.Business.Entities.SanPham", "SanPham")
                        .WithMany("ThuocTinhSanPhams")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinkyShopProject.Business.Entities.ThuocTinh", "ThuocTinh")
                        .WithMany("ThuocTinhSanPhams")
                        .HasForeignKey("IdThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.BienThe", b =>
                {
                    b.Navigation("BienTheChiTiets");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.GiaTri", b =>
                {
                    b.Navigation("BienTheChiTiets");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.SanPham", b =>
                {
                    b.Navigation("BienThes");

                    b.Navigation("ThuocTinhSanPhams");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.ThuocTinh", b =>
                {
                    b.Navigation("GiaTris");

                    b.Navigation("ThuocTinhSanPhams");
                });

            modelBuilder.Entity("MinkyShopProject.Business.Entities.ThuocTinhSanPham", b =>
                {
                    b.Navigation("BienTheChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
